name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS }}

          plugin_languages: yes
          plugin_languages_limit: 5
          plugin_languages_ignored: html, css
          plugin_languages_threshold: 2%
